import tkinter

root = tkinter.Tk()
root.geometry("1500x700")
root.title("questions")
questions = tkinter.Label(root, font=("arial Bold", 20), text="FIRST INFORMATION REPORT")
questions.grid(row=0, column=3,padx=45, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="1.District:")
questions.grid(row=1, column=0,padx=5, pady=10)
district_var = tkinter.StringVar()
district= tkinter.Entry(root, font=("arial Bold", 8), textvariable=district_var)
district.grid(row=1, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="P.S:")
questions.grid(row=3, column=0, padx=5, pady=20)
ps_var = tkinter.StringVar()
ps= tkinter.Entry(root, font=("arial Bold", 8), textvariable=ps_var)
ps.grid(row=3, column=1,padx=5, pady=10)

questions = tkinter.Label(root, font=("arial Bold", 8), text="Year:")
questions.grid(row=5, column=0, padx=5, pady=20)
year_var = tkinter.StringVar()
year= tkinter.Entry(root, font=("arial Bold", 8), textvariable=year_var)
year.grid(row=5, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="3.(a)Occurence of offence:")
questions.grid(row=7, column=0, padx=30, pady=10)
offence_var = tkinter.StringVar()
offence= tkinter.Entry(root, font=("arial Bold", 8), textvariable=offence_var)
offence.grid(row=7, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Time Period:")
questions.grid(row=9, column=0, padx=20, pady=20)
tp_var = tkinter.StringVar()
tp= tkinter.Entry(root, font=("arial Bold", 8), textvariable=tp_var)
tp.grid(row=9, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Date From:")
questions.grid(row=11, column=0, padx=20, pady=20)
df_var = tkinter.StringVar()
df= tkinter.Entry(root, font=("arial Bold", 8), textvariable=df_var)
df.grid(row=11  , column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Date To:")
questions.grid(row=13, column=0, padx=20, pady=20)
dt_var = tkinter.StringVar()
dt= tkinter.Entry(root, font=("arial Bold", 8), textvariable=dt_var)
dt.grid(row=13, column=1,padx=5, pady=10)

questions = tkinter.Label(root, font=("arial Bold", 8), text="Time from:")
questions.grid(row=15, column=0, padx=20, pady=20)
tf_var = tkinter.StringVar()
tf= tkinter.Entry(root, font=("arial Bold", 8), textvariable=tf_var)
tf.grid(row=15, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Time To:")
questions.grid(row=17, column=0, padx=20, pady=20)
tt_var = tkinter.StringVar()
tt= tkinter.Entry(root, font=("arial Bold", 8), textvariable=tt_var)
tt.grid(row=17, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(b)Information received at P.S:")
questions.grid(row=19, column=0, padx=20, pady=20)
receive_var = tkinter.StringVar()
receive= tkinter.Entry(root, font=("arial Bold", 8), textvariable=receive_var)
receive.grid(row=19, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Date:")
questions.grid(row=21, column=0, padx=20, pady=10)
date_var = tkinter.StringVar()
date= tkinter.Entry(root, font=("arial Bold", 8), textvariable=date_var)
date.grid(row=21, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Time:")
questions.grid(row=23, column=0, padx=20, pady=20)
time_var = tkinter.StringVar()
time= tkinter.Entry(root, font=("arial Bold", 8), textvariable=time_var)
time.grid(row=23, column=1,padx=5, pady=10)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(c)General Diary Reference:")
questions.grid(row=25, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Entry No.:")
questions.grid(row=27, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Date & Time :")
questions.grid(row=29, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="4.Type of Information:")
questions.grid(row=31, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="5.Place of Occurrence:")
questions.grid(row=33, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(a)Direction and distance from P.S:")
questions.grid(row=35, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(b)Address:")
questions.grid(row=37, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Beat no.:")
questions.grid(row=39, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(c)In case, outside the limit of this Police Station, then:")
questions.grid(row=41, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="Name od P.S:")
questions.grid(row=43, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="District(State):")
questions.grid(row=45, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="6.Complainant/Informant:")
questions.grid(row=47, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(a)Name:")
questions.grid(row=49, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(b)Father's/Husband's Name:")
questions.grid(row=51, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(c)Date/Year of Birth:")
questions.grid(row=53, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="(d)Nationality:")
questions.grid(row=55, column=0, padx=20, pady=20)
questions = tkinter.Label(root, font=("arial Bold", 8), text="UID No.:")
questions.grid(row=57, column=0, padx=20, pady=20)
# sb = tkinter.Scrollbar(root)
# sb.grid(row=0, column= 10,columnspan = 100)
root.mainloop()
