def form():
    import tkinter
    import customtkinter
    import fir
    customtkinter.set_appearance_mode("dark")  # Modes: system (default), light, dark
    customtkinter.set_default_color_theme("blue")  # Themes: blue (default), dark-blue, green
    root = customtkinter.CTk()

    root.geometry("1100x700")
    root.title("questions")
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 30), text="FIRST INFORMATION REPORT")
    questions.grid(row=0, column=3,padx=45, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="District :")
    questions.grid(row=1, column=0,padx=5, pady=10)
    district_var = customtkinter.StringVar()
    district= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=district_var)
    district.grid(row=1, column=1,padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Police Station :")
    questions.grid(row=1, column=3, padx=5, pady=10)
    ps_var = customtkinter.StringVar()
    ps= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=ps_var)
    ps.grid(row=1, column=4,padx=2, pady=10)

    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Year :")
    questions.grid(row=2, column=0, padx=5, pady=10)
    year_var = customtkinter.StringVar()
    year= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=year_var)
    year.grid(row=2, column=1,padx=5, pady=10)
    # questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 8), text="3.(a)Occurence of offence:")
    # questions.grid(row=7, column=0, padx=30, pady=10)
    # offence_var = customtkinter.StringVar()
    # offence= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=offence_var)
    # offence.grid(row=7, column=1,padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Time Period :")
    questions.grid(row=2, column=3, padx=20, pady=20)
    tp_var = customtkinter.StringVar()
    tp= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=tp_var)
    tp.grid(row=2, column=4,padx=5, pady=10)
    # questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 20), text="Date From:")
    # questions.grid(row=11, column=0, padx=20, pady=20)
    # df_var = customtkinter.StringVar()
    # df= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=df_var)
    # df.grid(row=11  , column=1,padx=5, pady=10)
    # questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 20), text="Date To:")
    # questions.grid(row=13, column=0, padx=20, pady=20)
    # dt_var = customtkinter.StringVar()
    # dt= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=dt_var)
    # dt.grid(row=13, column=1,padx=5, pady=10)

    # questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Time from:")
    # questions.grid(row=15, column=0, padx=20, pady=20)
    # tf_var = customtkinter.StringVar()
    # tf= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=tf_var)
    # tf.grid(row=15, column=1,padx=5, pady=10)
    # questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Time To:")
    # questions.grid(row=17, column=0, padx=20, pady=20)
    # tt_var = customtkinter.StringVar()
    # tt= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=tt_var)
    # tt.grid(row=17, column=1,padx=5, pady=10)
    #questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="(b)Information received at P.S:")
    #questions.grid(row=17, column=0, padx=20, pady=20)
    #receive_var = customtkinter.StringVar()
    #receive= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=receive_var)
    #receive.grid(row=17, column=1,padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="FIR NO :")
    questions.grid(row=3, column=0, padx=20, pady=10)
    firno_var = customtkinter.StringVar()
    firno= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=firno_var)
    firno.grid(row=3, column=1,padx=5, pady=10)
    #questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Time:")
    #questions.grid(row=3, column=3, padx=20, pady=20)
    #time_var = customtkinter.StringVar()
    #time= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=time_var)
    #time.grid(row=4, column=1,padx=5, pady=10)
    #questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="(c)General Diary Reference:")
    #questions.grid(row=23, column=0, padx=20, pady=20)
    #general_var = customtkinter.StringVar()
    #general= customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=general_var)
    #general.grid(row=23, column=1,padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Entry No :")
    questions.grid(row=3, column=3, padx=20, pady=20)
    entryno_var = customtkinter.StringVar()
    entryno = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=entryno_var)
    entryno.grid(row=3, column=4, padx=5, pady=10)

    # name
    # father's/husband's name
    # Date of birth
    # address
    # aadhar no
    # nationality
    # ipc
    # date
    # day
    # time period
    # type of information
    # complainant/informat
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Name :")
    questions.grid(row=4, column=0, padx=20, pady=20)
    name_var = customtkinter.StringVar()
    name = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=name_var)
    name.grid(row=4, column=1, padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Father's / Husband's Name :")
    questions.grid(row=4, column=3, padx=20, pady=20)
    fh_var = customtkinter.StringVar()
    fh = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=fh_var)
    fh.grid(row=4, column=4, padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Date of birth :")
    questions.grid(row=5, column=0, padx=20, pady=20)
    db_var = customtkinter.StringVar()
    db = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=db_var)
    db.grid(row=5, column=1, padx=5, pady=10)

    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Address :")
    questions.grid(row=5, column=3, padx=20, pady=20)
    add_var = customtkinter.StringVar()
    add = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=add_var)
    add.grid(row=5, column=4, padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Nationality :")
    questions.grid(row=6, column=0, padx=20, pady=20)
    nat_var = customtkinter.StringVar()
    nat = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=nat_var)
    nat.grid(row=6, column=1, padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Complaint / Imformat :")
    questions.grid(row=6, column=3, padx=20, pady=20)
    ci_var = customtkinter.StringVar()
    ci = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=ci_var)
    ci.grid(row=6, column=4, padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Date :")
    questions.grid(row=7, column=0, padx=20, pady=20)
    date_var = customtkinter.StringVar()
    date = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=date_var)
    date.grid(row=7, column=1, padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Day :")
    questions.grid(row=7, column=3, padx=20, pady=20)
    day_var = customtkinter.StringVar()
    day = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=day_var)
    day.grid(row=7, column=4, padx=5, pady=10)

    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Type of Information :")
    questions.grid(row=8, column=0, padx=20, pady=20)
    ti_var = customtkinter.StringVar()
    ti = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=ti_var)
    ti.grid(row=8, column=1, padx=5, pady=10)
    questions = customtkinter.CTkLabel(root, font=customtkinter.CTkFont("arial Bold", 13), text="Other Details :")
    questions.grid(row=8, column=3, padx=20, pady=20)
    other_var = customtkinter.StringVar()
    other = customtkinter.CTkEntry(root, font=customtkinter.CTkFont("arial Bold", 8), textvariable=other_var)
    other.grid(row=8, column=4, padx=5, pady=10)
    def exitt():
        global testfir
        testfir = fir.fir(district_var.get(), ps_var.get(), year_var.get(), tp_var.get(), firno_var.get(), entryno_var.get(), name_var.get(), fh_var.get(), db_var.get(), add_var.get(), nat_var.get(), ci_var.get(), date_var.get(), day_var.get(), ti_var.get(), other_var.get())
        # print(testfir)
        root.destroy()
        return testfir
    #btn=Button(root, text="SUBMIT", fg='blue', font=customtkinter.CTkFont("Forte", 30))
    #btn.place(x=120,y=350)
    #btn.grid(row=10, column=3, padx=20, pady=20)
    #btn = button(root, text = 'SUBMIT !', bd = '5',command = root.destroy)
    #btn.grid(row=10, column=3, padx=20, pady=20)
    button = customtkinter.CTkButton(root,command = exitt, text="Submit",font=customtkinter.CTkFont("arial Bold", 13))
    button.grid(row=9, column=3, padx=70, pady=60)
    root.mainloop()
    return testfir
