def form():
    import tkinter
    root = tkinter.Tk()

    root.geometry("1500x700")
    root.title("questions")
    questions = tkinter.Label(root, font=("arial Bold", 30), text="FIRST INFORMATION REPORT", bg="orange" , fg="blue")
    questions.grid(row=0, column=3,padx=45, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="District:")
    questions.grid(row=1, column=0,padx=5, pady=10)
    district_var = tkinter.StringVar()
    district= tkinter.Entry(root, font=("arial Bold", 8), textvariable=district_var)
    district.grid(row=1, column=1,padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Police Station:")
    questions.grid(row=1, column=3, padx=5, pady=10)
    ps_var = tkinter.StringVar()
    ps= tkinter.Entry(root, font=("arial Bold", 8), textvariable=ps_var)
    ps.grid(row=1, column=4,padx=2, pady=10)

    questions = tkinter.Label(root, font=("arial Bold", 13), text="Year:")
    questions.grid(row=2, column=0, padx=5, pady=10)
    year_var = tkinter.StringVar()
    year= tkinter.Entry(root, font=("arial Bold", 8), textvariable=year_var)
    year.grid(row=2, column=1,padx=5, pady=10)
    # questions = tkinter.Label(root, font=("arial Bold", 8), text="3.(a)Occurence of offence:")
    # questions.grid(row=7, column=0, padx=30, pady=10)
    # offence_var = tkinter.StringVar()
    # offence= tkinter.Entry(root, font=("arial Bold", 8), textvariable=offence_var)
    # offence.grid(row=7, column=1,padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Time Period:")
    questions.grid(row=2, column=3, padx=20, pady=20)
    tp_var = tkinter.StringVar()
    tp= tkinter.Entry(root, font=("arial Bold", 8), textvariable=tp_var)
    tp.grid(row=2, column=4,padx=5, pady=10)
    # questions = tkinter.Label(root, font=("arial Bold", 20), text="Date From:")
    # questions.grid(row=11, column=0, padx=20, pady=20)
    # df_var = tkinter.StringVar()
    # df= tkinter.Entry(root, font=("arial Bold", 8), textvariable=df_var)
    # df.grid(row=11  , column=1,padx=5, pady=10)
    # questions = tkinter.Label(root, font=("arial Bold", 20), text="Date To:")
    # questions.grid(row=13, column=0, padx=20, pady=20)
    # dt_var = tkinter.StringVar()
    # dt= tkinter.Entry(root, font=("arial Bold", 8), textvariable=dt_var)
    # dt.grid(row=13, column=1,padx=5, pady=10)

    # questions = tkinter.Label(root, font=("arial Bold", 13), text="Time from:")
    # questions.grid(row=15, column=0, padx=20, pady=20)
    # tf_var = tkinter.StringVar()
    # tf= tkinter.Entry(root, font=("arial Bold", 8), textvariable=tf_var)
    # tf.grid(row=15, column=1,padx=5, pady=10)
    # questions = tkinter.Label(root, font=("arial Bold", 13), text="Time To:")
    # questions.grid(row=17, column=0, padx=20, pady=20)
    # tt_var = tkinter.StringVar()
    # tt= tkinter.Entry(root, font=("arial Bold", 8), textvariable=tt_var)
    # tt.grid(row=17, column=1,padx=5, pady=10)
    #questions = tkinter.Label(root, font=("arial Bold", 13), text="(b)Information received at P.S:")
    #questions.grid(row=17, column=0, padx=20, pady=20)
    #receive_var = tkinter.StringVar()
    #receive= tkinter.Entry(root, font=("arial Bold", 8), textvariable=receive_var)
    #receive.grid(row=17, column=1,padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Date:")
    questions.grid(row=3, column=0, padx=20, pady=10)
    date_var = tkinter.StringVar()
    date= tkinter.Entry(root, font=("arial Bold", 8), textvariable=date_var)
    date.grid(row=3, column=1,padx=5, pady=10)
    #questions = tkinter.Label(root, font=("arial Bold", 13), text="Time:")
    #questions.grid(row=3, column=3, padx=20, pady=20)
    #time_var = tkinter.StringVar()
    #time= tkinter.Entry(root, font=("arial Bold", 8), textvariable=time_var)
    #time.grid(row=4, column=1,padx=5, pady=10)
    #questions = tkinter.Label(root, font=("arial Bold", 13), text="(c)General Diary Reference:")
    #questions.grid(row=23, column=0, padx=20, pady=20)
    #general_var = tkinter.StringVar()
    #general= tkinter.Entry(root, font=("arial Bold", 8), textvariable=general_var)
    #general.grid(row=23, column=1,padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Entry No:")
    questions.grid(row=3, column=3, padx=20, pady=20)
    entryno_var = tkinter.StringVar()
    entryno = tkinter.Entry(root, font=("arial Bold", 8), textvariable=entryno_var)
    entryno.grid(row=3, column=4, padx=5, pady=10)

    # name
    # father's/husband's name
    # Date of birth
    # address
    # aadhar no
    # nationality
    # ipc
    # date
    # day
    # time period
    # type of information
    # complainant/informat
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Name")
    questions.grid(row=4, column=0, padx=20, pady=20)
    name_var = tkinter.StringVar()
    name = tkinter.Entry(root, font=("arial Bold", 8), textvariable=name_var)
    name.grid(row=4, column=1, padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Father's / Husband's Name")
    questions.grid(row=4, column=3, padx=20, pady=20)
    fh_var = tkinter.StringVar()
    fh = tkinter.Entry(root, font=("arial Bold", 8), textvariable=fh_var)
    fh.grid(row=4, column=4, padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Date of birth")
    questions.grid(row=5, column=0, padx=20, pady=20)
    db_var = tkinter.StringVar()
    db = tkinter.Entry(root, font=("arial Bold", 8), textvariable=db_var)
    db.grid(row=5, column=1, padx=5, pady=10)

    questions = tkinter.Label(root, font=("arial Bold", 13), text="Address")
    questions.grid(row=5, column=3, padx=20, pady=20)
    add_var = tkinter.StringVar()
    add = tkinter.Entry(root, font=("arial Bold", 8), textvariable=add_var)
    add.grid(row=5, column=4, padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Nationality")
    questions.grid(row=6, column=0, padx=20, pady=20)
    nat_var = tkinter.StringVar()
    nat = tkinter.Entry(root, font=("arial Bold", 8), textvariable=nat_var)
    nat.grid(row=6, column=1, padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="I.P.C")
    questions.grid(row=6, column=3, padx=20, pady=20)
    ipc_var = tkinter.StringVar()
    ipc = tkinter.Entry(root, font=("arial Bold", 8), textvariable=ipc_var)
    ipc.grid(row=6, column=4, padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Date")
    questions.grid(row=7, column=0, padx=20, pady=20)
    date_var = tkinter.StringVar()
    date = tkinter.Entry(root, font=("arial Bold", 8), textvariable=date_var)
    date.grid(row=7, column=1, padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Day")
    questions.grid(row=7, column=3, padx=20, pady=20)
    day_var = tkinter.StringVar()
    day = tkinter.Entry(root, font=("arial Bold", 8), textvariable=day_var)
    day.grid(row=7, column=4, padx=5, pady=10)

    questions = tkinter.Label(root, font=("arial Bold", 13), text="Type of Information")
    questions.grid(row=8, column=0, padx=20, pady=20)
    ti_var = tkinter.StringVar()
    ti = tkinter.Entry(root, font=("arial Bold", 8), textvariable=ti_var)
    ti.grid(row=8, column=1, padx=5, pady=10)
    questions = tkinter.Label(root, font=("arial Bold", 13), text="Complaint / Imformat")
    questions.grid(row=8, column=3, padx=20, pady=20)
    ci_var = tkinter.StringVar()
    ci = tkinter.Entry(root, font=("arial Bold", 8), textvariable=ci_var)
    ci.grid(row=8, column=4, padx=5, pady=10)

    #btn=Button(root, text="SUBMIT", fg='blue', font=("Forte", 30))
    #btn.place(x=120,y=350)
    #btn.grid(row=10, column=3, padx=20, pady=20)
    #btn = button(root, text = 'SUBMIT !', bd = '5',command = root.destroy)
    #btn.grid(row=10, column=3, padx=20, pady=20)
    button = tkinter.Button(root, text="Submit",fg='red',font=("arial Bold", 13))
    button.grid(row=9, column=3, padx=70, pady=60)

    root.mainloop()
